# permissions for end users to view prometheuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-viewer-role
rules:
- apiGroups:
  - monitoring.core.example.com
  resources:
  - prometheuses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.core.example.com
  resources:
  - prometheuses/status
  verbs:
  - get
